social:
  - identifier: github
    name: GitHub
    url: https://github.com/Jeremy-Hibiki
    params:
      icon: brand-github
  # - identifier: twitter
  #   name: Twitter
  #   url: https://twitter.com
  #   params:
  #     icon: brand-twitter
