mainSections:
  - post
rssFullContent: true
footer:
  since: 2020
  customText: <a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener">沪ICP备2022016216号</a>
dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006 15:04 MST
sidebar:
  avatar:
    enabled: true
    src: 'https://avatars.githubusercontent.com/u/62326866?v=4'
    local: false
article:
  math: true
  toc: true
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0
widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc
defaultImage:
  opengraph:
    enabled: false
    local: false
    src: ""
colorScheme:
  toggle: true
  default: dark
imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
